<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>flow build output</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#errors</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#flow_target_line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#flow_build_info</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#flow_haxe_ver</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#flow_logs</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#haxe_trace_line</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>errors</key>
		<dict>
			<key>match</key>
			<string>(?:(^.*[.]hx):(\d+): (?:characters|lines) (\d+)-).+
</string>
			<key>name</key>
			<string>invalid.error.flow-build-output</string>
		</dict>
		<key>flow_build_info</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.logging.flow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(flow \/ )(build only, )?(debug = true)</string>
			<key>name</key>
			<string>meta.logging.flow</string>
		</dict>
		<key>flow_haxe_ver</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.logging.flow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.haxe_version.flow</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.haxe_version.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(flow \/ )(haxe version )(\d+.\d+.\d+)</string>
			<key>name</key>
			<string>meta.logging.flow</string>
		</dict>
		<key>flow_logs</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.logging.flow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.log_type.flow</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(flow \/ )(.+ - )?(.+)</string>
			<key>name</key>
			<string>meta.logging.flow</string>
		</dict>
		<key>flow_target_line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.logging.flow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.target.flow</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.target_arch.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(flow \/ )(target) is (mac|linux|windows|web|android) \( (.+) \)</string>
			<key>name</key>
			<string>meta.logging.flow</string>
		</dict>
		<key>haxe_trace_line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.trace_filename.flow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(.+\.hx)[:](\d+)[:]</string>
			<key>name</key>
			<string>meta.logging.flow</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.flow-build-output</string>
	<key>uuid</key>
	<string>a7f13cbf-e607-408a-802f-bfa6e909d299</string>
</dict>
</plist>
