<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>flow</string>
	</array>
	<key>name</key>
	<string>flow file</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keyword_objects</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword_roots</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword_arrays</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric_values</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bool_values</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_values</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#normal_objects</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#normal_numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#normal_bools</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bool_values</key>
		<dict>
			<key>match</key>
			<string>\"?\b(true|false)\b\"?</string>
			<key>name</key>
			<string>constant.numeric.flow</string>
		</dict>
		<key>keyword_arrays</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.keyword_arrays.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\"?\b(flags|defines)\b\"?(?:.*[:]\s*[\[])</string>
			<key>name</key>
			<string>meta.keyword_arrays.flow</string>
		</dict>
		<key>keyword_objects</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.keyword_objects.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\"?\b(dependencies|flags|defines|web|mobile|ios|android|libs|native)\b\"?(?:.*[:]\s*[{])</string>
			<key>name</key>
			<string>meta.keyword_objects.flow</string>
		</dict>
		<key>keyword_roots</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.keyword_roots.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\"?\b(project|flow|app|build|files|if)\"?\b\"?(?:.*[:]\s*[{])</string>
			<key>name</key>
			<string>meta.keyword_roots.flow</string>
		</dict>
		<key>keyword_string</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.definition.keyword_string.flow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.keyword_string.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\"?\b(name|version|author|package|icon)\b\"?\s*[:]\s*(['].*[']|["].*["])</string>
			<key>name</key>
			<string>meta.keyword_string.flow</string>
		</dict>
		<key>normal_numeric</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.identifier.normal_numeric.flow</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.normal_numeric.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\"?\b(.*)\b\"?\s*[:]\s*([0-9])</string>
			<key>name</key>
			<string>meta.normal_numeric.flow</string>
		</dict>
		<key>normal_objects</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.normal_objects.flow</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\"?\b(.*)\b\"?(?:.*[:]\s*[{])</string>
			<key>name</key>
			<string>meta.normal_objects.flow</string>
		</dict>
		<key>numeric_values</key>
		<dict>
			<key>match</key>
			<string>\"?\b([0-9])\b\"?</string>
			<key>name</key>
			<string>constant.numeric.flow</string>
		</dict>
		<key>string_values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>("|')</string>
					<key>end</key>
					<string>("|')</string>
					<key>name</key>
					<string>string.quoted.flow</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.flow</string>
	<key>uuid</key>
	<string>dda0dbdd-79ee-4944-a477-0b74c43d65b1</string>
</dict>
</plist>
